<?php
/**
 * capital - Client.php
 * Create by ALCINDOR LOSTHELVEN
 * Created on: 9/3/2020
 */

namespace app\DefaultApp\Models;


use systeme\Model\Model;

class Client extends Model
{
    private $id, $id_institution, $nom, $prenom, $telephone, $email;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getIdInstitution()
    {
        return $this->id_institution;
    }

    /**
     * @param mixed $id_institution
     */
    public function setIdInstitution($id_institution)
    {
        $this->id_institution = $id_institution;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * @param mixed $prenom
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;
    }

    /**
     * @return mixed
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param mixed $telephone
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }


    private function existe($nom, $prenom)
    {
        $con = self::connection();
        $req = "SELECT *FROM client WHERE nom=:nom and prenom=:prenom";
        $stmt = $con->prepare($req);
        $stmt->execute(array(
            ":nom" => $nom,
            ":prenom" => $prenom
        ));
        $res = $stmt->fetchAll(\PDO::FETCH_CLASS, __CLASS__);
        if (count($res) > 0) {
            return true;
        } else {
            return false;
        }
    }

    public function add()
    {
        if ($this->existe($this->nom, $this->prenom)) {
            return "Client existe";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public static function dernierId()
    {
        $con = self::connection();
        $req = "select id from client  ORDER BY id DESC LIMIT 1";
        $rps = $con->query($req);
        $data = $rps->fetch();
        $id = $data['id'];
        return $id;
    }

    public static function listerParInstitution($id_institution){
        $con = self::connection();
        $req = "SELECT *FROM client WHERE id_institution=:id_institution";
        $stmt = $con->prepare($req);
        $stmt->execute(array(
            ":id_institution" => $id_institution
        ));
        return $stmt->fetchAll(\PDO::FETCH_CLASS, __CLASS__);
    }
}