<?php
/**
 * capital - Station.php
 * Create by ALCINDOR LOSTHELVEN
 * Created on: 9/4/2020
 */

namespace app\DefaultApp\Models;


use systeme\Model\Model;

class Station extends Model
{

    private $id,$nom,$addresse,$longitude,$latitude;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getAddresse()
    {
        return $this->addresse;
    }

    /**
     * @param mixed $addresse
     */
    public function setAddresse($addresse)
    {
        $this->addresse = $addresse;
    }

    /**
     * @return mixed
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * @param mixed $longitude
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;
    }

    /**
     * @return mixed
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * @param mixed $latitude
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;
    }

    private function existe($nom)
    {
        $con = self::connection();
        $req = "SELECT *FROM station WHERE nom=:nom";
        $stmt = $con->prepare($req);
        $stmt->execute(array(
            ":nom" => $nom
        ));
        $res = $stmt->fetchAll(\PDO::FETCH_CLASS, __CLASS__);
        if (count($res) > 0) {
            return true;
        } else {
            return false;
        }
    }

    public function add()
    {
        if ($this->existe($this->nom)) {
            return "Station existe";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }

}